name: fitnessbuddyandroid
description: The best fitness tracker app.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  charts_flutter: ^0.12.0
  image_picker: ^0.8.5+3
  fl_chart: ^0.55.2
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.7
  location: ^4.2.0
  geolocator: ^7.0.3
  flutter_svg: ^1.1.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_database: ^10.0.3
  firebase_storage: ^11.0.3
  firebase_crashlytics: ^3.0.3
  pedometer: ^3.0.0
  quick_actions: ^1.0.0

  #mapbox_gl: ^0.16.0

  google_fonts: ^2.0.0
  intl: ^0.17.0
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3
  stop_watch_timer: ^1.1.0+1

  permission_handler: ^10.2.0
  cloud_functions: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Bold.ttf